WorldName: 'Spheres'
MinimumHeight: 34
MaximumHeight: 96
MinimumRadius: 8
MaximumRadius: 32
GlassType: 1
UseGlowstone: false
SphereSpawnChance: 80
WorldSeed: 12345
SphereSeed: 12345
GlassBlockID: 20
AirBlockID: 0
UseWorldFloor: false
FloorUsesWater: false
VerboseConsoleOutput: false
WorldType: 'NORMAL'
PreserveStrongholds: true
PreserveVillages: true
PreserveTemples: true
OreBubbles:
  Gold:
    SpawnBubbles: true
    MinimumHeight: 34
    MaximumHeight: 96
    MinimumRadius: 3
    MaximumRadius: 4
    SpawnChance: 35
    ShellBlockID: 1
  Iron:
    SpawnBubbles: true
    MinimumHeight: 34
    MaximumHeight: 96
    MinimumRadius: 4
    MaximumRadius: 5
    SpawnChance: 80
    ShellBlockID: 1
  Coal:
    SpawnBubbles: true
    MinimumHeight: 34
    MaximumHeight: 96
    MinimumRadius: 5
    MaximumRadius: 7
    SpawnChance: 80
    ShellBlockID: 1
  Lapis:
    SpawnBubbles: true
    MinimumHeight: 34
    MaximumHeight: 96
    MinimumRadius: 5
    MaximumRadius: 8
    SpawnChance: 50
    ShellBlockID: 1
  Diamond:
    SpawnBubbles: true
    MinimumHeight: 34
    MaximumHeight: 96
    MinimumRadius: 3
    MaximumRadius: 4
    SpawnChance: 30
    ShellBlockID: 1
  Redstone:
    SpawnBubbles: true
    MinimumHeight: 34
    MaximumHeight: 96
    MinimumRadius: 4
    MaximumRadius: 6
    SpawnChance: 50
    ShellBlockID: 1
  Emerald:
    SpawnBubbles: true
    MinimumHeight: 34
    MaximumHeight: 96
    MinimumRadius: 3
    MaximumRadius: 4
    SpawnChance: 25
    ShellBlockID: 1
  Netherrack:
    SpawnBubbles: true
    MinimumHeight: 34
    MaximumHeight: 96
    MinimumRadius: 10
    MaximumRadius: 16
    SpawnChance: 45
    ShellBlockID: 1
  SoulSand:
    SpawnBubbles: true
    MinimumHeight: 34
    MaximumHeight: 96
    MinimumRadius: 10
    MaximumRadius: 16
    SpawnChance: 45
    ShellBlockID: 1
  Glowstone:
    SpawnBubbles: true
    MinimumHeight: 34
    MaximumHeight: 96
    MinimumRadius: 10
    MaximumRadius: 16
    SpawnChance: 50
    ShellBlockID: 1
  EndStone:
    SpawnBubbles: true
    MinimumHeight: 34
    MaximumHeight: 96
    MinimumRadius: 10
    MaximumRadius: 16
    SpawnChance: 35
    ShellBlockID: 1
  Sand:
    SpawnBubbles: true
    MinimumHeight: 34
    MaximumHeight: 96
    MinimumRadius: 8
    MaximumRadius: 12
    SpawnChance: 40
    ShellBlockID: 1
  Clay:
    SpawnBubbles: true
    MinimumHeight: 34
    MaximumHeight: 96
    MinimumRadius: 8
    MaximumRadius: 12
    SpawnChance: 45
    ShellBlockID: 1
  MossStone:
    SpawnBubbles: true
    MinimumHeight: 34
    MaximumHeight: 96
    MinimumRadius: 6
    MaximumRadius: 10
    SpawnChance: 40
    ShellBlockID: 1
  Obsidian:
    SpawnBubbles: true
    MinimumHeight: 34
    MaximumHeight: 96
    MinimumRadius: 6
    MaximumRadius: 10
    SpawnChance: 35
    ShellBlockID: 1
