WorldName: 'Spheres'
MinimumHeight: 34
MaximumHeight: 96
MinimumRadius: 8
MaximumRadius: 32
GlassType: 1
UseGlowstone: false
SphereSpawnChance: 80
WorldSeed: 12345
SphereSeed: 12345
GlassBlockID: 20
UseWorldFloor: false
FloorUsesWater: false
VerboseConsoleOutput: false
WorldType: 'NORMAL'

