# The name of the world this plugin generates.
WorldName: 'Spheres'
# Minimum and maximum elevations to spawn spheres at.
MinimumHeight: 34
MaximumHeight: 96
# Minimum and maximum possible radii for the spheres.
# This should roughly equate to radius * 2 for the size.
MinimumRadius: 8
MaximumRadius: 32
# Type of glass bubble to spawn.
# 0: No glass
# 1: A full sphere
# 2: A half sphere (glass only below sea level)
GlassType: 1
# If enabled, will spawn the sphere with two glowstone "rings"
# in the glass, along a vertical axis.
UseGlowstone: false
# Percent chance to spawn a sphere.
SphereSpawnChance: 80
# Seed used to generate the world the spheres are in.
WorldSeed: 12345
# Seed used to determine the location, size, etc. of
# all spheres and ore spheres.
SphereSeed: 12345
# The block ids to use for glass (the bubble)
# and air (the material surrounding the bubble).
GlassBlockID: 20
AirBlockID: 0
# If enabled, will spawn a bedrock floor at y = 0.
UseWorldFloor: false
# If enabled, and if UseWorldFloor is enabled, will spawn
# a layer of water at y = 1.
FloorUsesWater: false
# Verbose debug output. Will be removed once the plugin is stable
# and functional.
VerboseConsoleOutput: false
# World generation type. Currently, it will allow for
# the normal world, the nether, and the end.
WorldType: 'NORMAL'
# Protection settings. If enabled, spheres will be generated to prevent
# each feature from being destroyed.
PreserveStrongholds: true
PreserveVillages: true
PreserveTemples: true

# Resource bubble settings. Similar to the normal settings, only per resource.
# To add new type of resource bubbles, just copy an existing resource and
# modify the name and settings.
Meteors:
  Water:
    # Whether or not to spawn this type of bubble.
    SpawnBubbles: true
    MinimumHeight: 34
    MaximumHeight: 96
    MinimumRadius: 8
    MaximumRadius: 12
    SpawnChance: 40
    # The block ID used as the bubble's "shell", in a similar fashion to
    # the glass used by the default plugin.
    ShellBlockID: 1
    # The block ID used as the bubble's interior.
    CoreBlockID: 9
  Lava:
    SpawnBubbles: true
    MinimumHeight: 34
    MaximumHeight: 96
    MinimumRadius: 8
    MaximumRadius: 12
    SpawnChance: 35
    ShellBlockID: 1
    CoreBlockID: 11
  Sand:
    SpawnBubbles: true
    MinimumHeight: 34
    MaximumHeight: 96
    MinimumRadius: 8
    MaximumRadius: 12
    SpawnChance: 40
    ShellBlockID: 1
    CoreBlockID: 12
  Gold:
    SpawnBubbles: true
    MinimumHeight: 34
    MaximumHeight: 96
    MinimumRadius: 3
    MaximumRadius: 4
    SpawnChance: 35
    ShellBlockID: 1
    CoreBlockID: 14
  Iron:
    SpawnBubbles: true
    MinimumHeight: 34
    MaximumHeight: 96
    MinimumRadius: 4
    MaximumRadius: 5
    SpawnChance: 80
    ShellBlockID: 1
    CoreBlockID: 15
  Coal:
    SpawnBubbles: true
    MinimumHeight: 34
    MaximumHeight: 96
    MinimumRadius: 5
    MaximumRadius: 7
    SpawnChance: 80
    ShellBlockID: 1
    CoreBlockID: 16
  Lapis:
    SpawnBubbles: true
    MinimumHeight: 34
    MaximumHeight: 96
    MinimumRadius: 5
    MaximumRadius: 8
    SpawnChance: 50
    ShellBlockID: 1
    CoreBlockID: 21
  MossStone:
    SpawnBubbles: true
    MinimumHeight: 34
    MaximumHeight: 96
    MinimumRadius: 6
    MaximumRadius: 10
    SpawnChance: 40
    ShellBlockID: 1
    CoreBlockID: 48
  Obsidian:
    SpawnBubbles: true
    MinimumHeight: 34
    MaximumHeight: 96
    MinimumRadius: 6
    MaximumRadius: 10
    SpawnChance: 35
    ShellBlockID: 1
    CoreBlockID: 49
  Diamond:
    SpawnBubbles: true
    MinimumHeight: 34
    MaximumHeight: 96
    MinimumRadius: 3
    MaximumRadius: 4
    SpawnChance: 30
    ShellBlockID: 1
    CoreBlockID: 56
  Redstone:
    SpawnBubbles: true
    MinimumHeight: 34
    MaximumHeight: 96
    MinimumRadius: 4
    MaximumRadius: 6
    SpawnChance: 50
    ShellBlockID: 1
    CoreBlockID: 73
  Clay:
    SpawnBubbles: true
    MinimumHeight: 34
    MaximumHeight: 96
    MinimumRadius: 8
    MaximumRadius: 12
    SpawnChance: 45
    ShellBlockID: 1
    CoreBlockID: 82
  Netherrack:
    SpawnBubbles: true
    MinimumHeight: 34
    MaximumHeight: 96
    MinimumRadius: 10
    MaximumRadius: 16
    SpawnChance: 45
    ShellBlockID: 1
    CoreBlockID: 87
  SoulSand:
    SpawnBubbles: true
    MinimumHeight: 34
    MaximumHeight: 96
    MinimumRadius: 10
    MaximumRadius: 16
    SpawnChance: 45
    ShellBlockID: 1
    CoreBlockID: 88
  Glowstone:
    SpawnBubbles: true
    MinimumHeight: 34
    MaximumHeight: 96
    MinimumRadius: 10
    MaximumRadius: 16
    SpawnChance: 50
    ShellBlockID: 1
    CoreBlockID: 89
  EndStone:
    SpawnBubbles: true
    MinimumHeight: 34
    MaximumHeight: 96
    MinimumRadius: 10
    MaximumRadius: 16
    SpawnChance: 35
    ShellBlockID: 1
    CoreBlockID: 121
  Emerald:
    SpawnBubbles: true
    MinimumHeight: 34
    MaximumHeight: 96
    MinimumRadius: 3
    MaximumRadius: 4
    SpawnChance: 25
    ShellBlockID: 1
    CoreBlockID: 129
