world: 'sphere'
useglass: true
usehalfglass: false
userandomglass: false
usefloor: true
killonfloor: true
dobridges: true
useglow: false
mindist: 100
minheight: 34
maxheight: 96
minradius: 8
maxradius: 32
worldsize: 2000
worldseed: 12345
sphereseed: 12345
spherechance: 80
glassblock: 20
bridgetype: 1
otherworld: false
potprotect: true
sphereprotect: false
floorprotect: false
nowater: true
nofloorspawn: true
autosavechunklist: true
autosaveinterval: 30

